i"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
from datetime import timedelta
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-)fco!f=4av$myoncn*gp2a=f*a6+!uixzp3ycu7%wj^k(3w%rd'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_simplejwt',
    'core',
    'doctor',
    'patient',
    'inventory',
    'corsheaders',
    ]

# CORS_ALLOWED_ORIGINS = ['https://210b-2401-4900-4e1e-b829-29a8-cd62-8555-34b1.ngrok-free.app']
CORS_ALLOW_ALL_ORIGINS = True


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'src.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'src.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'medi_mind',
        'USER': 'root',
        'PASSWORD': 'Admin123!',
        'HOST': '13.202.5.147',
        'PORT': '3306',
    }
}



# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

# USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

AUTH_USER_MODEL = 'core.User'

#from django.contrib.auth.models import Group
#USER_TYPE_GROUP_MAP = {record['name'].lower():record['id'] for record in Group.objects.values()}
#The above equation is used to generate the USER_TYPE_GROUP_MAP dynamically

USER_TYPE_GROUP_MAP = {
    'admin'          : 1,
    'branch_manager' : 6,
    'staff'          : 3,
    'patient'        : 4,
    'pharmacist'     : 5,
    'doctor'         : 2,

}

OPENAPI_KEY = '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'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=30),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=31),
    'SIGNING_KEY': SECRET_KEY,
    'ALGORITHM' : 'HS256',
    'USER_ID_CLAIM' : 'user_id',

}  

# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.gmail.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'luckychat0123@gmail.com'  # Your Gmail address
# EMAIL_HOST_PASSWORD = 'cvpp qifh dxpr stag'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'ravilla.anil3@gmail.com'  # Your Gmail address
EMAIL_HOST_PASSWORD = 'udzz zglq opxs zvck' 


#T_SID = 'ACec6246e5c57c78a483762dc839304b44'
#T_TOKEN = '96b6bb614ba62899c6997d8f97413a97'

#INTERAKT_API_KEY = "bDVOUVZZY2dDdlRKWmo3LTBiOGtZTVY1TFhDVkx4RndiOGFubktmQ2dTTTo="

#AWS_ACCESS_KEY_ID = 'AKIAW3MEBSXBN2OCMIL6' #'AKIAW3MEBSXBMRGD36LH' 
#AWS_SECRET_ACCESS_KEY = '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' #'DvQQxgabiiT7Wsd+xesnjJKmrmiOyI4Tv/ErLCtY' 
#AWS_STORAGE_BUCKET_NAME = 'medimind-app'
#AWS_S3_SIGNATURE_NAME = 's3v4',
AWS_S3_REGION_NAME = 'ap-south-1'
AWS_S3_FILE_OVERWRITE = False
AWS_DEFAULT_ACL =  None
AWS_S3_VERIFY = True
DEFAULT_FILE_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'
